global:
  load_from_base_dir: true
  target_model: "./"
  tokenizer: "./"
  datasets:
    - json_train_path: "./train_subset.json"
      json_test_path: "./test_subset.json"
  batch_size: 1
  seed: 42
  device: "cuda"  # This will use all available GPUs
  fpr_thresholds:
    - 0.1
    - 0.01
    - 0.001
  n_bootstrap_samples: 10
  test_samples: null
  max_length: 512
  cache_dir: null


loss:
  module: loss
  mc_num: 4

# loss-calibration:
#   module: "ratio"
#   reference_model_path: "Dream-org/Dream-v0-Base-7B"
#   reference_device: "cuda"

zlib:
  module: zlib

# lowercase:
#  module: lowercase

Sama:
  module: "sama"
  steps: 4
  subset_size: 8
  num_subsets: 128
  l_schedule: "linear"
  min_mask_frac: 0.05
  max_mask_frac: 0.50
  batch_size: 8
  max_length: 512
  reference_model_path: "Dream-org/Dream-v0-Base-7B"
  reference_device: "cuda"
  seed: 42
  save_metadata: false
  metadata_dir: ""


Its:
  module: "its"
  steps: 4
  subset_size: 8
  num_subsets: 128
  l_schedule: "linear"
  min_mask_frac: 0.05
  max_mask_frac: 0.50
  lambda_penalty: 0.1
  weight_start_layer_ratio: 0
  weight_end_layer_ratio: 1
  batch_size: 8
  max_length: 512
  reference_model_path: "Dream-org/Dream-v0-Base-7B"
  reference_device: "cuda"
  seed: 42
  save_metadata: false
  metadata_dir: ""
