run_name: Dream-v0-Base-7B-pretrained-mimir-arxiv-lora
wandb_project: Diff_LLM
wandb_group: SAMA

dataset:
  train:
    type: local
    path: ./mimir-arxiv/train.json
  test:
    type: local
    path: ./mimir-arxiv/test.json

tokenizer:
  identifier: Dream-org/Dream-v0-Base-7B
  max_length: 512

model:
  identifier: Dream-org/Dream-v0-Base-7B
  load_pretrained: true

lora:
  enabled: true
  r: 64
  lora_alpha: 64
  lora_dropout: 0.
  target_modules: ["q_proj", "k_proj", "v_proj"  ]
  bias: "none"
  task_type: "CAUSAL_LM"
  save_merged_model_at_end: true

training:
  output_dir: ./Dream-v0-Base-7B-pretrained-mimir-arxiv-1_6_1.0e-4_10_512-lora-attn1
  batch_size: 1
  gradient_accumulation_steps: 6
  learning_rate: 1.0e-4
  weight_decay: 0.1
  warmup_steps: 500
  num_train_epochs: 10
  max_steps: -1
  eval_strategy: epoch
  save_strategy: "no"
  logging_strategy: epoch
  save_total_limit: 1
  bf16: true
  fp16: false
  gradient_checkpointing: true
