run_name: LLaDA-8B-Base-pretrained-mimir-arxiv
wandb_project: Diff_LLM
wandb_group: SAMA

dataset:
  train:
    type: local
    path: ./mimir-arxiv/train.json
  # val not provided -> We'll use test for val
  test:
    type: local
    path: ./mimir-arxiv/test.json

tokenizer:
  identifier: GSAI-ML/LLaDA-8B-Base
  max_length: 512

model:
  identifier: GSAI-ML/LLaDA-8B-Base
  load_pretrained: true


lora:
  enabled: true
  r: 128
  lora_alpha: 256
  lora_dropout: 0.
  target_modules: ["ff_proj", "up_proj", "ff_out"  ]

training:
  output_dir: ./LLaDA-8B-Base-pretrained-mimir-arxiv-4_12_1.0e-4_10_512-lora-mlpr128
  # deepspeed_config: ./trainer/configs/ds_config.json
  batch_size: 4
  gradient_accumulation_steps: 12
  learning_rate: 1.0e-4
  weight_decay: 0.01
  warmup_steps: 50
  num_train_epochs: 10         # For epoch-based training
  max_steps: -1                # Must be -1 to fully rely on epochs
  eval_strategy: epoch
  save_strategy: "no"
  logging_strategy: epoch
  save_total_limit: 1
  bf16: true
  fp16: false
  #early_stopping_patience: 3
  #early_stopping_threshold: 0.001